<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Enter' => 'Escribe',
  'Select' => 'Selecciona',
  'You should provide modelClass in constructor of EditableSaver.'=>'Debes especificar un modelClass en el constructor de EditableSaver',
  'Property "attribute" should be defined.'=>'La propiedad "attribute" debe ser definida',
  'Property "primaryKey" should be defined.'=>'La propiedad "primaryKey" debe ser definida',
  'Model {class} not found by primary key "{pk}"'=>'El modelo {class} no se ha encontrado vía la clave primaria "{pk}"',
  'Model {class} does not have attribute "{attr}"'=>'El modelo {class} no posee el atributo "{attr}"',
  'Model {class} rules do not allow to update attribute "{attr}"'=>'Las reglas del modelo {class} no permiten la actualización del atributo "{attr}"',
  'Error while saving record!'=>'Error mientras se guardaba el registro!',

);
